spring:
  application:
    name: gateway-service
  cloud:
      gateway:
        # 配置路由规则, 访问当前网关的 /server/* 会转发请求到 http://localhost:9091/server/*
        routes:
        # 路由Id, 需要唯一
        - id: service-com.can.route
          uri: http://localhost:9091
          predicates:
          - Path=/server/*
server:
  port: 10101

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      # 向服务端的注册地址
      defaultZone: http://eureka-8081.com:8081/eureka/,http://eureka-8082.com:8082/eureka

