spring:
  application:
    name: eureka-client-two

# 修改端口, 防止和服务端端口冲突
server:
  port: 9091

eureka:
  client:
    service-url:
      # 向服务端的注册地址
      defaultZone: http://eureka-8081.com:8081/eureka/,http://eureka-8082.com:8082/eureka