spring:
  application:
    name: eureka-server-one

server:
  port: 8081

eureka:
  instance:
    hostname: eureka-8081.com
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      # 向另外一个服务端注册自己，如果有多个服务端，通过逗号分隔就行了
      defaultZone: http://eureka-8082.com:8082/eureka/



